language: node_js

node_js:
- '10'

script:
- npm run lint
- npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  fqdn: weather.salomvary.com
  on:
    branch: master
